services:

  Lectures.Repository:
    class : ../../../core/Lecture/infrastructure/persistance/MongoLectureRepository
    arguments: ['@Shared.ConnectionManager']

  Lectures.GetController:
    class : ../../controllers/Lecture/LectureGetController
    arguments: ['@Lectures.Repository']